// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrk_zedk7SQSqDz9EICeOFa716OJ-Mi34',
    appId: '1:132617572880:web:f7db00cf93a30c6f003095',
    messagingSenderId: '132617572880',
    projectId: 'fir-cli-2976d',
    authDomain: 'fir-cli-2976d.firebaseapp.com',
    storageBucket: 'fir-cli-2976d.appspot.com',
    measurementId: 'G-07VQ1PJKE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnQ4iJ6lhG5MWiOtShnhUcRBgSLu1Ung4',
    appId: '1:132617572880:android:acab608a5f41877e003095',
    messagingSenderId: '132617572880',
    projectId: 'fir-cli-2976d',
    storageBucket: 'fir-cli-2976d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB53LMgE-6jvbE8jd-Kfq8mFyz5ioj64j0',
    appId: '1:132617572880:ios:83e349222a454ad4003095',
    messagingSenderId: '132617572880',
    projectId: 'fir-cli-2976d',
    storageBucket: 'fir-cli-2976d.appspot.com',
    iosClientId: '132617572880-otqnm2n6kb1k44bngc6ij3r87boaa9ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTestProjectFirebaseCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB53LMgE-6jvbE8jd-Kfq8mFyz5ioj64j0',
    appId: '1:132617572880:ios:26df804f92b8e0b0003095',
    messagingSenderId: '132617572880',
    projectId: 'fir-cli-2976d',
    storageBucket: 'fir-cli-2976d.appspot.com',
    iosClientId: '132617572880-cfmjkm0g5jkd8fp667foi60gtt4so2g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTestProjectFirebaseCli.RunnerTests',
  );
}
